"""Summarise recon_rows_v0.json into the tables used by the recon note.

Per target-channel (A only) and per archive:instrument — total on-star
spectra, era, in-window counts at each rung (0.1 AU / 2.5 Rsun /
1.2 Rsun), distinct events covered, nearest |dt| to any t_ca, band, and
which laser-line families (266/355/532/1064/1550 nm) the band contains.
Also the per-event ledger: for every deep-family channel-A event with any
in-window spectrum, the list of instruments and their smallest |dt|.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from astropy.time import Time

HERE = Path(__file__).resolve().parents[1]
rows = json.load(open(HERE / "results" / "recon_rows_v0.json"))
scan = json.load(open(HERE / "results" / "recon_scan_v0.json"))
LINES = {"266": 266.0, "355": 355.0, "532": 532.0, "1064": 1064.0, "1550": 1550.0}
ONSTAR = scan["onstar_arcsec"]


def lines_in(band):
    if not band:
        return ""
    lo, hi = band
    return "/".join(k for k, v in LINES.items() if lo <= v <= hi)


def dedupe_key(r):
    # MAROON-X blue/red arms, ESO raw vs phase3 of the same exposure, CADC raw vs
    # processed planes: collapse to (archive-family, instrument, minute)
    fam = r["archive"].split("/")[0].split("-")[0]
    t = round(r["t_mid_mjd"] * 1440) if r.get("t_mid_mjd") is not None else None
    return (r["target_id"], fam, r["instrument"], t)


out_lines = []
P = out_lines.append
P("# Spectral-archive recon summary (generated by recon_summary.py)\n")

per_target_inst = defaultdict(lambda: defaultdict(lambda: {"n": 0, "t0": None, "t1": None, "w01": set(), "w25": set(), "w12": set(),
                                                             "n01": 0, "n25": 0, "n12": 0, "mindt": None, "band": None, "public": set()}))
seen = set()
event_ledger = defaultdict(lambda: defaultdict(lambda: {"n": 0, "mindt": None, "rungs": set()}))
for r in rows:
    if r["sep_arcsec"] > ONSTAR or r.get("t_mid_mjd") is None:
        continue
    k = dedupe_key(r)
    if k in seen:
        continue
    seen.add(k)
    fam = r["archive"].split("/")[0].split("-")[0]
    key = f"{fam}:{r['instrument']}"
    s = per_target_inst[r["target_id"]][key]
    s["n"] += 1
    t = r["t_mid_mjd"]
    s["t0"] = t if s["t0"] is None else min(s["t0"], t)
    s["t1"] = t if s["t1"] is None else max(s["t1"], t)
    d = r.get("nearest_event_dt_days")
    if d is not None and (s["mindt"] is None or abs(d) < abs(s["mindt"])):
        s["mindt"] = d
    if r.get("band_nm"):
        s["band"] = r["band_nm"]
    s["public"].add(str(r.get("public")))
    iw = r.get("in_window") or {}
    for rung, tag in (("0.1AU", "01"), ("2.5Rsun", "25"), ("1.2Rsun", "12")):
        if rung in iw:
            s[f"n{tag}"] += 1
            s[f"w{tag}"].add(iw[rung])
    if iw:
        eid = iw.get("0.1AU") or next(iter(iw.values()))
        e = event_ledger[(r["target_id"], eid)][key]
        e["n"] += 1
        e["rungs"] |= set(iw.keys())
        if e["mindt"] is None or abs(d) < abs(e["mindt"]):
            e["mindt"] = d

P("## Per target x instrument (on-star, deduplicated per minute; A channel)\n")
P("| target | archive:instrument | N | era | in 0.1 AU (N / events) | in 2.5 Rsun | in 1.2 Rsun | nearest dt (d) | band nm | lines | public |")
P("|---|---|---|---|---|---|---|---|---|---|---|")
for tid in sorted(per_target_inst):
    for key, s in sorted(per_target_inst[tid].items(), key=lambda kv: -kv[1]["n"]):
        era = f"{Time(s['t0'], format='mjd').isot[:7]}→{Time(s['t1'], format='mjd').isot[:7]}"
        band = f"{s['band'][0]:.0f}–{s['band'][1]:.0f}" if s["band"] else "?"
        P(f"| {tid} | {key} | {s['n']} | {era} | {s['n01']} / {len(s['w01'])} | {s['n25']} / {len(s['w25'])} | {s['n12']} / {len(s['w12'])} | "
          f"{s['mindt']:+.2f} | {band} | {lines_in(s['band'])} | {','.join(sorted(s['public']))} |")

P("\n## Event ledger (every channel-A event with >= 1 in-window on-star spectrum)\n")
P("| target | event | t_ca | b (Rsun) | instrument | N in-window | rungs | min |dt| (h) |")
P("|---|---|---|---|---|---|---|---|")
evinfo = {}
for tid, td in scan["targets"].items():
    for e in td["events"]:
        evinfo[(tid, e["event_id"])] = e
for (tid, eid) in sorted(event_ledger, key=lambda k: (k[0], evinfo[k]["t_ca_mjd"])):
    e = evinfo[(tid, eid)]
    for key, s in sorted(event_ledger[(tid, eid)].items()):
        P(f"| {tid} | {eid} | {e['t_ca_utc'][:10]} | {e['b_rsun']:.2f} | {key} | {s['n']} | {'+'.join(sorted(s['rungs']))} | {abs(s['mindt'])*24:.1f} |")

# grazing-rung hits in detail
P("\n## Grazing-rung (<= 2.5 Rsun window) spectra, one line each\n")
P("| target | UTC mid | archive:instrument | exp (s) | dt (h) | rungs | target name | ident |")
P("|---|---|---|---|---|---|---|---|")
seen2 = set()
for r in sorted(rows, key=lambda r: (r["target_id"], r.get("t_mid_mjd") or 0)):
    iw = r.get("in_window") or {}
    if "2.5Rsun" in iw or "1.2Rsun" in iw:
        k = dedupe_key(r)
        if k in seen2:
            continue
        seen2.add(k)
        P(f"| {r['target_id']} | {Time(r['t_mid_mjd'], format='mjd').isot[:16]} | {r['archive']}:{r['instrument']} | {r['exptime_s']:.0f} | "
          f"{r['nearest_event_dt_days']*24:+.1f} | {'+'.join(sorted(iw))} | {r['target_name']} | {r['ident']} |")

# archive errors
P("\n## Archive errors recorded\n")
for tid, td in scan["targets"].items():
    if td["archive_errors"]:
        P(f"- {tid}: " + "; ".join(f"{a}: {str(e)[:120]}" for a, e in td["archive_errors"].items()))

(HERE / "results" / "recon_summary_v0.md").write_text("\n".join(out_lines) + "\n")
print("\n".join(out_lines))
