[project]
name = "sgl-seti-survey"
version = "0.1.0"
requires-python = ">=3.12.2"
dependencies = [
    "sglseti",
    "astropy>=6.0",
    "requests>=2.31",
    "scipy>=1.18.0",
    "pyyaml>=6.0.3",
    "pypdf>=6.16.1",
    "astro-datalab==2.22.1",
    "pandas>=3.0.5",
    "skypatrol==0.6.21",
    "k2fov>=8.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8",
]

[tool.uv.sources]
sglseti = { path = "../sglseti", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["sglsurvey"]
