"""Step I: report tables generated from the ledger (v2 plan §8.4).

Reads the v2 records and analysis products, reconciles counts, and
writes surveys/wise/results/report_tables.md plus a JSON with every
number the v4 report quotes. The build FAILS (non-zero exit) on a
count mismatch between the ledger and the analysis products or on an
unresolved supersession link.

Usage: uv run python surveys/wise/scripts/report_tables.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import v2common as C  # noqa: E402

from sglsurvey.records import read_records  # noqa: E402

BANDS = ("W1", "W2", "W3", "W4")


def fmt(x, nd=2):
    return "—" if x is None or (isinstance(x, float) and not np.isfinite(x)) else f"{x:.{nd}f}"


def main() -> int:
    freeze = C.load_freeze()
    out = {"freeze_content_hash": freeze["freeze_content_hash"], "freeze_hash": C.freeze_hash()}
    errors = []
    lines = ["---", 'title: "WISE v2 — report tables (generated from the ledger)"', "date: 2026-08-22",
             "---", "", f"Freeze `{freeze['freeze_content_hash'][:23]}…`; generated by "
             "`surveys/wise/scripts/report_tables.py` — do not edit by hand.", ""]
    # ---- null ensembles / candidates --------------------------------------------
    for s in ("dev", "confirmatory"):
        p = C.NULL_DIR / f"{s}_null_ensemble.json"
        if not p.exists():
            out[s] = None
            continue
        ne = json.loads(p.read_text())
        prim = ne["primary"]
        o = {"n_endpoints": prim["n_endpoints"], "n_cells": prim["n_cells"],
             "n_void": prim["n_null_unstable"], "n_heavy_tail": prim.get("n_null_heavy_tail"),
             "R_fwer": prim["fwer"]["R_fwer"], "n_candidates": prim["n_candidates"],
             "candidates": prim["candidates"], "n_real_R_gt_1": prim["n_real_R_gt_1"],
             "expected_R_gt_1": prim["expected_R_gt_1_from_ring"],
             "holdout_null": prim["holdout_null_calibration"],
             "n_ring_vs_traj_fail": prim.get("n_ring_vs_trajectory_ks_fail"),
             "n_two_phase": prim["n_two_phase_cells"], "n_phase_ks_fail": prim["n_phase_scramble_ks_fail"],
             "real_R_quantiles": prim["real_R_quantiles"],
             "mask_sensitivity": ne.get("mask_sensitivity")}
        # per-band void counts and top cells by R~
        cells = prim["cells"]
        o["void_by_band"] = Counter(k.split("/")[2] for k, v in cells.items() if v["null_unstable"])
        o["cells_by_band"] = Counter(k.split("/")[2] for k in cells)
        top = sorted([(v["R_norm"], k) for k, v in cells.items() if v["R_norm"] is not None and not v["null_unstable"]],
                     reverse=True)[:10]
        o["top_cells"] = [{"cell": k, "R_norm": r, "R": cells[k]["R"], "global_p": cells[k]["global_p"],
                           "p_cell": cells[k]["rank"]["p_cell"], "p_phase": cells[k].get("p_phase"),
                           "p_traj": cells[k].get("p_trajectory"), "S_phase": cells[k]["S_phase"]}
                          for r, k in top]
        # adjudication
        adj = C.RUN_DIR / "records" / f"adjudication_{s}.json"
        o["adjudication"] = json.loads(adj.read_text()) if adj.exists() else None
        cand_path = C.RUN_DIR / "records" / f"candidate_{s}.jsonl"
        cands = read_records(cand_path) if cand_path.exists() else []
        if o["adjudication"] and len(cands) != o["adjudication"]["n_candidates"]:
            errors.append(f"{s}: candidate records {len(cands)} != adjudication count {o['adjudication']['n_candidates']}")
        if len(cands) != prim["n_candidates"] and o["adjudication"]:
            errors.append(f"{s}: null-ensemble candidates {prim['n_candidates']} != candidate records {len(cands)}")
        o["candidate_records"] = [{"cell": f"{c['endpoint_id']}/{c['role']}/{c['extra']['band']}",
                                   "status": c["status"], "global_p": c["global_p_value"],
                                   "R_norm": c["model_comparison"]["R_norm"],
                                   "phase": c["annotations"]["parallax_phase"]["signature"],
                                   "loss": c["extra"].get("selection_function_loss")} for c in cands]
        # completeness
        cp = C.RUN_DIR / "completeness" / f"{s}_completeness.json"
        if cp.exists():
            comp = json.loads(cp.read_text())
            o["completeness_summary"] = comp["summary"]
            # per band, per model median m90 (threshold & final) across cells and intervals
            med = {}
            for band in BANDS:
                for kind in ("threshold", "final_candidate"):
                    for model in C.TEMPORAL_MODELS:
                        vals = []
                        for k, c in comp["cells"].items():
                            if not k.endswith("/" + band) or c["null_unstable"]:
                                continue
                            res = c[kind].get(model, {})
                            if res.get("status") == "ok":
                                vals += [iv["m90"] for iv in res["intervals"] if iv["m90"] is not None]
                        med[f"{band}/{kind}/{model}"] = (float(np.median(vals)) if vals else None, len(vals))
            o["m90_medians"] = med
            o["prf_throughput_median"] = comp["summary"]["median_prf_throughput"]
            o["vetoes_on_injections"] = comp["summary"]["vetoes_fired_total"]
            # injection true-pass rate of the hold-out test (threshold-recovered injections)
            n_t = sum(c["n_threshold"] for c in comp["cells"].values())
            n_s = sum(c["vetoes_fired"].get("static_flux_consistent", 0) for c in comp["cells"].values())
            hb = {m: [0, 0] for m in C.TEMPORAL_MODELS}
            for c in comp["cells"].values():
                for m, v in c.get("holdout_annotation", {}).get("by_model", {}).items():
                    hb[m][0] += v["n"]; hb[m][1] += v["pass"]
            o["injection_test_rates"] = {"n_threshold_recovered": n_t,
                                         "holdout_pass_by_model": {m: (v[1] / v[0] if v[0] else None) for m, v in hb.items()},
                                         "static_fail_fraction": (n_s / n_t) if n_t else None}
        out[s] = o
    # ---- ledger reconciliation ------------------------------------------------
    rec_dir = C.RUN_DIR / "records"
    cons = read_records(rec_dir / "constraint.jsonl") if (rec_dir / "constraint.jsonl").exists() else []
    runs = read_records(rec_dir / "analysis_run.jsonl") if (rec_dir / "analysis_run.jsonl").exists() else []
    run_ids = {r["analysis_run_id"] for r in runs}
    by_set = defaultdict(Counter)
    for c in cons:
        if c["analysis_run_id"] not in run_ids:
            errors.append(f"constraint {c['constraint_id']} references unknown run {c['analysis_run_id']}")
        by_set[c["extra"]["set"]][(c["completeness_kind"], c["kind"])] += 1
    v1_ids = set()
    v1_path = C.V1_CAL / "records" / "constraint.jsonl"
    if v1_path.exists():
        v1_ids = {r["constraint_id"] for r in read_records(v1_path)}
    n_sup = sum(1 for c in cons if c.get("supersedes"))
    bad = [c["constraint_id"] for c in cons if c.get("supersedes") and c["supersedes"] not in v1_ids]
    if bad:
        errors.append(f"{len(bad)} supersession links do not resolve to v1 constraint ids")
    out["ledger"] = {"n_analysis_runs": len(runs), "n_constraints": len(cons),
                     "by_set": {s: {f"{k[0]}/{k[1]}": v for k, v in cnt.items()} for s, cnt in by_set.items()},
                     "n_superseding_v1": n_sup, "v1_constraints": len(v1_ids)}
    for s in ("dev", "confirmatory"):
        if out.get(s) and out[s].get("completeness_summary"):
            n_led = sum(by_set[s].values())
            n_prod = out[s]["completeness_summary"]["n_constraints"]
            if n_led != n_prod:
                errors.append(f"{s}: ledger constraints {n_led} != completeness product {n_prod}")
    # ---- geometry / control ---------------------------------------------------
    gp = C.RUN_DIR / "geometry" / "covariance_envelopes.json"
    out["geometry"] = json.loads(gp.read_text())["summary"] if gp.exists() else None
    cp = C.RUN_DIR / "control" / "14000" / "summary.json"
    out["control"] = json.loads(cp.read_text()) if cp.exists() else None
    op = C.RUN_DIR / "observer" / "summary.json"
    out["observer"] = json.loads(op.read_text()) if op.exists() else None
    # ---- markdown --------------------------------------------------------------
    for s in ("confirmatory", "dev"):
        o = out.get(s)
        if not o:
            continue
        title = "Confirmatory set (blind, once)" if s == "confirmatory" else "Development set (exploratory)"
        lines += [f"## {title}", "",
                  f"| quantity | value |", "| --- | --- |",
                  f"| endpoints / cells | {o['n_endpoints']} / {o['n_cells']} |",
                  f"| cells void (unstable / heavy-tail) | {o['n_void']} ({o['n_heavy_tail']} heavy-tail) — by band {dict(o['void_by_band'])} |",
                  f"| R̃_FWER (α = 0.05) | {fmt(o['R_fwer'], 3)} |",
                  f"| cells with R > 1 (v1-style exceedances) | {o['n_real_R_gt_1']} (ring expectation {fmt(o['expected_R_gt_1'], 1)}) |",
                  f"| candidates (R̃ ≥ R̃_FWER) | {o['n_candidates']} {o['candidates']} |",
                  f"| hold-out test null false-pass rate | {fmt(o['holdout_null'].get('false_pass_rate'), 3)} "
                  f"({o['holdout_null'].get('n_null_trajectories')} null trajectories; above q95: "
                  f"{fmt(o['holdout_null'].get('false_pass_rate_above_q95'), 3)}) |"]
        if o.get("injection_test_rates"):
            it = o["injection_test_rates"]
            lines.append(f"| hold-out test pass rate on threshold-recovered injections (annotation) | "
                         f"{ {m: (None if v is None else round(v, 3)) for m, v in it['holdout_pass_by_model'].items()} } |")
            lines.append(f"| static flux-consistent veto fired on threshold-recovered injections | {fmt(it['static_fail_fraction'], 3)} (n = {it['n_threshold_recovered']}) |")
        if o.get("prf_throughput_median") is not None:
            lines.append(f"| median PRF-vs-Gaussian throughput of injections | {fmt(o['prf_throughput_median'], 3)} |")
        lines += ["", "Top cells by R̃:", "", "| cell | R̃ | R | global p | p_cell (48) | p_phase | p_traj | S phase 0 / 1 |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- |"]
        for t in o["top_cells"]:
            lines.append(f"| {t['cell']} | {fmt(t['R_norm'])} | {fmt(t['R'])} | {fmt(t['global_p'], 3)} | "
                         f"{fmt(t['p_cell'], 3)} | {fmt(t['p_phase'], 3)} | {fmt(t['p_traj'], 3)} | "
                         f"{fmt(t['S_phase'][0], 1)} / {fmt(t['S_phase'][1], 1)} |")
        if o.get("candidate_records"):
            lines += ["", "Candidates:", "", "| cell | status | R̃ | global p | phase | test loss |", "| --- | --- | --- | --- | --- | --- |"]
            for c in o["candidate_records"]:
                lines.append(f"| {c['cell']} | {c['status']} | {fmt(c['R_norm'])} | {fmt(c['global_p'], 3)} | {c['phase']} | {c['loss']} |")
        if o.get("m90_medians"):
            lines += ["", "Median m90 over cells × intervals (Vega), threshold / final-candidate, per temporal model:", "",
                      "| band | model | threshold m90 (n) | final-candidate m90 (n) |", "| --- | --- | --- | --- |"]
            for band in BANDS:
                for model in C.TEMPORAL_MODELS:
                    a = o["m90_medians"].get(f"{band}/threshold/{model}", (None, 0))
                    b = o["m90_medians"].get(f"{band}/final_candidate/{model}", (None, 0))
                    lines.append(f"| {band} | {model} | {fmt(a[0])} ({a[1]}) | {fmt(b[0])} ({b[1]}) |")
        if o.get("mask_sensitivity"):
            ms = o["mask_sensitivity"]
            lines += ["", f"Quality-mask sensitivity ({ms['n_common_cells']} common cells): R̃_FWER "
                      f"{ {k: round(v, 3) for k, v in ms['R_fwer'].items()} }; candidates {ms['n_candidates']}; "
                      f"ΔR vs primary {ms['delta_R_vs_primary']}"]
        lines.append("")
    lines += ["## Ledger", "", f"AnalysisRuns: {out['ledger']['n_analysis_runs']}; Constraints: {out['ledger']['n_constraints']} "
              f"({out['ledger']['by_set']}); superseding v1 records: {out['ledger']['n_superseding_v1']} of "
              f"{out['ledger']['v1_constraints']} v1 constraints.", ""]
    if out.get("geometry"):
        g = out["geometry"]
        lines += ["## Geometry", "", f"Cross-track cells: {g['n_cross_track_cells']} of {g['n_pairs']} "
                  f"(max σ_xt,99 {fmt(g['max_sigma_xt_99_overall'], 4)}″ vs threshold {g['threshold_arcsec']}″); "
                  f"independent check: median {fmt(g['independent_check']['median_residual_arcsec'], 4)}″, "
                  f"max {fmt(g['independent_check']['max_residual_arcsec'], 3)}″.", ""]
    if out.get("control"):
        c = out["control"]
        lines += ["## Positive control (asteroid 14000)", ""]
        for b in ("W1", "W2"):
            if b in c:
                x = c[b]
                lines.append(f"- {b}: {x['n_epochs']} frames, S_max {fmt(x['S_max_real'], 1)}, T {fmt(x['T_designated'], 1)}, "
                             f"R {fmt(x['R_real'])}, R̃ {fmt(x['R_norm_real'])}, rank p {fmt(x['rank_statement']['p_cell'], 3)}, "
                             f"peak offset {x['peak_offset_arcsec']}″, stack mag {fmt(x['recovered_stack_mag'])}, "
                             f"throughput vs pipeline {fmt(x['throughput_vs_pipeline']['median_dmag'])} mag "
                             f"(MAD {fmt(x['throughput_vs_pipeline']['mad_dmag'])}, n = {x['throughput_vs_pipeline']['n']})")
        lines.append("")
    if errors:
        lines += ["## BUILD ERRORS", ""] + [f"- {e}" for e in errors]
    C.RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    (C.RESULTS_DIR / "report_tables.md").write_text("\n".join(lines) + "\n")
    (C.RESULTS_DIR / "report_numbers.json").write_text(json.dumps(out, indent=1, default=str))
    print("\n".join(lines))
    if errors:
        print("\nBUILD FAILED:", *errors, sep="\n  ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
