"""Programme ledger v2 — merge the per-report harvest into one table plus
the shared Constraint / AnalysisRun / Candidate records (plan goal 5).

Inputs:  surveys/programme-ledger/harvest/*.yaml            transcribed rows (tracked; see harvest/SCHEMA.md)
         runs/programme-ledger/v2/harvest_generated/*.yaml  per-record Pipeline A rows (scripts/harvest/pipeline_a_*.py)
Outputs: runs/programme-ledger/v2/programme_ledger_v2.ecsv               full table (28k rows)
         surveys/programme-ledger/results/programme_ledger_v2_crossings.ecsv  Pipeline B + programme-wide rows (tracked)
         surveys/programme-ledger/results/programme_ledger_v2_summary.json
         surveys/programme-ledger/results/programme_ledger_v2_matrix.json
         runs/programme-ledger/v2/records/{analysis_run,constraint,candidate}.jsonl
         runs/programme-ledger/v2/manifest.json

The ledger is an index of what the reports state; it never re-derives a
limit. Every row carries the report/results citation it came from.

Usage: uv run python surveys/programme-ledger/scripts/build_ledger_v2.py
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from itertools import product
from pathlib import Path

import numpy as np
import yaml
from astropy.table import Table

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from sglseti import canonical_json, load_target_registry, stable_id  # noqa: E402

from sglsurvey.manifest import build_manifest, write_manifest  # noqa: E402
from sglsurvey.records import (AnalysisRun, Candidate, Constraint,  # noqa: E402
                               append_records, to_jsonl_line)

HARVEST = ROOT / "surveys/programme-ledger/harvest"          # transcribed (tracked)
RESULTS = ROOT / "surveys/programme-ledger/results"
RUN_DIR = ROOT / "runs/programme-ledger/v2"
HARVEST_GEN = RUN_DIR / "harvest_generated"                     # per-record Pipeline A rows (regenerated by scripts/harvest/pipeline_a_*.py)
REGISTRY = ROOT / "registries/pilot_wise_2026.yaml"
LEDGER_VERSION = "2.0.0"

STATUSES = ("searched", "constraint_only", "ledger_only", "not_constrainable",
            "structurally_open", "vetoed_known_source", "retained_ambiguous",
            "no_survey")
CHANNELS = ("A", "B", "S1", "S2", "corridor")
RUNG_AU = {"1.2 Rsun": 0.00558, "2.5 Rsun": 0.01163, "0.1 AU": 0.1,
           "0.90 AU": 0.90, "0.95 AU": 0.95, "1.0 AU": 1.0}
RUNGS_OF_CHANNEL = {"A": ("1.2 Rsun", "2.5 Rsun", "0.1 AU", "1.0 AU"),  # grazing A rungs: LAT only "B": ("1.2 Rsun", "2.5 Rsun", "0.1 AU", "1.0 AU"),
                    "S1": ("1.2 Rsun", "2.5 Rsun", "0.1 AU"),
                    "S2": ("1.2 Rsun", "2.5 Rsun", "0.1 AU", "0.90 AU", "0.95 AU", "1.0 AU")}
ROLE_OF_CHANNEL = {"A": "uplink_interception_opposition",
                   "B": "downlink_prelens_antipode",
                   "S1": "downlink_postlens_sunward",
                   "S2": "uplink_past_sun_conjunction",
                   "corridor": "focal_line_corridor"}
# Constraint.kind vocabulary (records.py): recovery_curve | qualified_null | not_constrainable
CONSTRAINT_KIND = {"searched": "recovery_curve", "constraint_only": "qualified_null",
                   "ledger_only": "qualified_null", "not_constrainable": "not_constrainable"}
CANDIDATE_STATUS = {"retained_ambiguous": "retained_ambiguous",
                    "vetoed_known_source": "rejected"}
# ordering of coverage states from best to worst, for the per-cell "best state"
STATE_RANK = {s: i for i, s in enumerate(
    ("searched", "retained_ambiguous", "vetoed_known_source", "constraint_only",
     "ledger_only", "structurally_open", "no_survey", "not_constrainable"))}

_NUM = re.compile(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?")


def git_commit(path: Path) -> dict:
    try:
        rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=path, capture_output=True,
                             text=True, check=True).stdout.strip()
        dirty = bool(subprocess.run(["git", "status", "--porcelain"], cwd=path,
                                    capture_output=True, text=True).stdout.strip())
        return {"commit": rev, "dirty": dirty}
    except Exception as exc:  # noqa: BLE001
        return {"commit": None, "dirty": None, "error": str(exc)}


def _listify(value):
    if value is None:
        return [None]
    if isinstance(value, (list, tuple)):
        return list(value)
    return [value]


def _range_lo_hi(text):
    """Parse 'min–max' (any dash) into two floats; None if not a range."""
    if text is None:
        return (None, None)
    nums = [float(x) for x in _NUM.findall(str(text))]
    if len(nums) >= 2:
        return (min(nums[:2]), max(nums[:2]))
    if len(nums) == 1:
        return (nums[0], nums[0])
    return (None, None)


_ZINT = re.compile(r"(\d+(?:\.\d+)?)\s*[-–—]\s*(\d+(?:\.\d+)?)\s*AU")


def _z_interval(rung: str):
    """Corridor rows carry a z interval string ('550-10000 AU', any dash);
    crossings rows carry a beam radius rung, whose relay-distance interval is
    the programme's 550–10,000 AU prior."""
    m = _ZINT.search(str(rung or ""))
    if m and str(rung) not in RUNG_AU:
        lo, hi = float(m.group(1)), float(m.group(2))
        if hi >= 100:
            return (lo, hi)
    return (550.0, 10000.0)


def _rung_class(channel, rung):
    """Coarse rung family for census tables."""
    rung = str(rung or "")
    if channel == "corridor":
        return "corridor"
    if rung in ("1.2 Rsun", "2.5 Rsun"):
        return "grazing"
    if rung == "0.1 AU":
        return "0.1 AU"
    if rung in ("0.90 AU", "0.95 AU"):
        return "sub-1 AU skirt"
    if rung == "1.0 AU":
        return "1.0 AU"
    return "any"


def load_harvest():
    files = sorted(HARVEST.glob("*.yaml")) + sorted(HARVEST_GEN.glob("*.yaml"))
    surveys = []
    for f in files:
        d = yaml.safe_load(f.read_text())
        d["_file"] = f
        surveys.append(d)
    return surveys


def explode_rows(surveys, registry_ids):
    """One flat row per (target, channel, rung) combination of each harvest
    row; list-valued fields are expanded and the harvest row keeps an id."""
    flat, problems, warnings = [], [], []
    for s in surveys:
        for i, r in enumerate(s.get("rows") or []):
            hid = f"{s['survey_id']}#{i:03d}"
            if r.get("status") not in STATUSES:
                problems.append(f"{hid}: status {r.get('status')!r} not in vocabulary")
            targets = _listify(r.get("target_id"))
            channels = _listify(r.get("channel"))
            rungs = _listify(r.get("rung"))
            for ch in channels:
                if ch not in CHANNELS:
                    problems.append(f"{hid}: channel {ch!r} not in vocabulary")
            for t in targets:
                if t not in registry_ids and t != "programme":
                    problems.append(f"{hid}: target {t!r} not in registry")
            for ch, rung in product(channels, rungs):
                if ch in RUNGS_OF_CHANNEL and str(rung) not in RUNGS_OF_CHANNEL[ch]:
                    warnings.append(f"{hid}: rung {rung!r} unusual for channel {ch}")
            group_n = len(targets) * len(channels) * len(rungs)
            for t, ch, rung in product(targets, channels, rungs):
                lo, hi = _range_lo_hi(r.get("limit_range"))
                plo, phi = _range_lo_hi(r.get("power_mw_range"))
                if r.get("power_mw") is not None:
                    plo = phi = float(r["power_mw"])
                flat.append({
                    "harvest_id": hid, "group_size": group_n,
                    "survey_id": s["survey_id"], "pipeline": s.get("pipeline") or "",
                    "plan_section": str(s.get("plan_section") or ""),
                    "archives": ",".join(str(a) for a in _listify(s.get("archives")) if a),
                    "hypothesis_version": str(s.get("hypothesis_version") or ""),
                    "report": str(s.get("report") or ""),
                    "target_id": t or "", "channel": ch or "", "rung": str(rung or ""),
                    "rung_au": RUNG_AU.get(str(rung), np.nan),
                    "rung_class": _rung_class(ch, rung),
                    "band": str(r.get("band") or "any"),
                    "substrate": str(r.get("substrate") or ""),
                    "status": r.get("status") or "",
                    "limit_kind": str(r.get("limit_kind") or ""),
                    "limit_value": float(r["limit_value"]) if r.get("limit_value") is not None else np.nan,
                    "limit_unit": str(r.get("limit_unit") or ""),
                    "limit_lo": lo if lo is not None else np.nan,
                    "limit_hi": hi if hi is not None else np.nan,
                    "power_mw": float(r["power_mw"]) if r.get("power_mw") is not None else np.nan,
                    "power_mw_lo": plo if plo is not None else np.nan,
                    "power_mw_hi": phi if phi is not None else np.nan,
                    "n_events": int(r["n_events"]) if r.get("n_events") is not None else -1,
                    "n_trials": int(r["n_trials"]) if r.get("n_trials") is not None else -1,
                    "epoch_range": str(r.get("epoch_range") or ""),
                    "source": str(r.get("source") or ""),
                    "notes": str(r.get("notes") or ""),
                })
    for w in warnings:
        print("warning:", w)
    return flat, problems


def best_power(rows):
    """Best (lowest) transmitter-power limit among rows, MW; None if none."""
    vals = [r["power_mw"] for r in rows if np.isfinite(r["power_mw"])]
    vals += [r["power_mw_hi"] for r in rows if np.isfinite(r["power_mw_hi"]) and not np.isfinite(r["power_mw"])]
    return float(min(vals)) if vals else None


def build_matrix(flat, registry_ids):
    """Per target × channel × rung: best coverage state, best MW limit,
    contributing surveys. Programme-wide rows apply to every target but are
    kept apart (they are statements about the whole list, not a target)."""
    cells = defaultdict(list)
    for r in flat:
        cells[(r["target_id"], r["channel"], r["rung"])].append(r)
    matrix = {}
    for (t, ch, rung), rows in cells.items():
        rows_sorted = sorted(rows, key=lambda r: STATE_RANK.get(r["status"], 99))
        best = rows_sorted[0]["status"]
        bp = best_power([r for r in rows if r["status"] in ("searched", "constraint_only")])
        matrix.setdefault(t, {})[f"{ch}|{rung}"] = {
            "best_state": best,
            "states": dict(Counter(r["status"] for r in rows)),
            "best_power_mw": bp,
            "best_power_survey": (min((r for r in rows if r["status"] in ("searched", "constraint_only")
                                       and (np.isfinite(r["power_mw"]) or np.isfinite(r["power_mw_hi"]))),
                                      key=lambda r: r["power_mw"] if np.isfinite(r["power_mw"]) else r["power_mw_hi"],
                                      default={"survey_id": None})["survey_id"]),
            "surveys": sorted({r["survey_id"] for r in rows}),
            "bands": sorted({r["band"] for r in rows}),
        }
    return matrix


def make_records(surveys, flat, registry, env):
    started = datetime.now(timezone.utc).isoformat()
    runs, cons, cands = [], [], []
    run_by_survey = {}
    for s in surveys:
        report = ROOT / str(s.get("report") or "")
        rep_hash = ("sha256:" + __import__("hashlib").sha256(report.read_bytes()).hexdigest()) if report.is_file() else "missing"
        harvest_hash = "sha256:" + __import__("hashlib").sha256(s["_file"].read_bytes()).hexdigest()
        config = {"survey_id": s["survey_id"], "plan_section": s.get("plan_section"),
                  "pipeline": s.get("pipeline"), "archives": s.get("archives"),
                  "harvest_file": str(s["_file"].relative_to(ROOT)), "harvest_sha256": harvest_hash,
                  "ledger_version": LEDGER_VERSION}
        run = AnalysisRun(
            analysis_run_id=stable_id("run", {"config": config, "report": rep_hash,
                                              "registry": registry.source_hash}),
            pipeline_id="programme-ledger-harvest", pipeline_version=LEDGER_VERSION,
            config=config, observation_set_hash=rep_hash, intersection_set_hash=rep_hash,
            registry_source_hash=registry.source_hash,
            hypothesis_version=str(s.get("hypothesis_version") or "n/a"),
            environment=env, random_seeds={}, started_utc=started,
            finished_utc=datetime.now(timezone.utc).isoformat(),
            output_files={"ledger": "runs/programme-ledger/v2/programme_ledger_v2.ecsv",
                          "ledger_crossings": "surveys/programme-ledger/results/programme_ledger_v2_crossings.ecsv"},
            warning_summary=("index of published statements; limits are not re-derived",))
        runs.append(run)
        run_by_survey[s["survey_id"]] = run.analysis_run_id
    for r in flat:
        rid = run_by_survey[r["survey_id"]]
        extra = {k: (None if isinstance(v, float) and not np.isfinite(v) else v)
                 for k, v in r.items()}
        if r["status"] in CONSTRAINT_KIND:
            kind = CONSTRAINT_KIND[r["status"]]
            limit = None
            if np.isfinite(r["limit_value"]) or np.isfinite(r["limit_hi"]):
                limit = {"value": r["limit_value"] if np.isfinite(r["limit_value"]) else None,
                         "range": [r["limit_lo"], r["limit_hi"]] if np.isfinite(r["limit_hi"]) else None,
                         "unit": r["limit_unit"], "kind": r["limit_kind"],
                         "transmitter_power_mw": r["power_mw"] if np.isfinite(r["power_mw"]) else None,
                         "transmitter_power_mw_range": [r["power_mw_lo"], r["power_mw_hi"]] if np.isfinite(r["power_mw_hi"]) else None,
                         "physical_interpretation": "as stated in the cited report section"}
            elif np.isfinite(r["power_mw"]) or np.isfinite(r["power_mw_hi"]):
                limit = {"value": None, "unit": r["limit_unit"], "kind": r["limit_kind"],
                         "transmitter_power_mw": r["power_mw"] if np.isfinite(r["power_mw"]) else None,
                         "transmitter_power_mw_range": [r["power_mw_lo"], r["power_mw_hi"]] if np.isfinite(r["power_mw_hi"]) else None,
                         "physical_interpretation": "as stated in the cited report section"}
            if kind == "recovery_curve" and limit is None:
                kind = "qualified_null"
            cons.append(Constraint(
                constraint_id=stable_id("con", {"endpoint": r["target_id"], "role": ROLE_OF_CHANNEL[r["channel"]],
                                                "band": r["band"], "rung": r["rung"], "kind": kind,
                                                "survey": r["survey_id"], "harvest": r["harvest_id"],
                                                "ledger": LEDGER_VERSION}),
                analysis_run_id=rid, endpoint_id=r["target_id"], role=ROLE_OF_CHANNEL[r["channel"]],
                hypothesis_version=r["hypothesis_version"] or "n/a",
                z_interval_au=_z_interval(r["rung"]), band=r["band"], epoch_range_mjd=(0.0, 0.0),
                duty_cycle_range=(1.0, 1.0), residual_motion_bound_arcsec_per_yr=0.0,
                morphology="point source", kind=kind,
                recovery_probability=0.9 if kind == "recovery_curve" else None,
                flux_limit=limit, injection_summary_ref=r["source"], false_alarm_rate=None,
                trials_accounting_ref=r["report"], extra=extra,
                completeness_kind="threshold" if kind == "recovery_curve" else None))
        elif r["status"] in CANDIDATE_STATUS:
            cands.append(Candidate(
                candidate_id=stable_id("cnd", {"endpoint": r["target_id"], "role": ROLE_OF_CHANNEL[r["channel"]],
                                               "band": r["band"], "rung": r["rung"], "survey": r["survey_id"],
                                               "harvest": r["harvest_id"], "ledger": LEDGER_VERSION}),
                analysis_run_id=rid, endpoint_id=r["target_id"], role=ROLE_OF_CHANNEL[r["channel"]],
                observation_ids=(), measurements_ref=r["source"],
                status=CANDIDATE_STATUS[r["status"]],
                veto_reason="known_source" if r["status"] == "vetoed_known_source" else None,
                rejection_test="catalogued source coincidence" if r["status"] == "vetoed_known_source" else None,
                extra=extra, annotations={"notes": r["notes"]}))
    return runs, cons, cands


def main() -> int:
    registry = load_target_registry(REGISTRY)
    registry_ids = set(registry.ids) if not callable(registry.ids) else set(registry.ids())
    surveys = load_harvest()
    flat, problems = explode_rows(surveys, registry_ids)
    if problems:
        print("HARVEST PROBLEMS:")
        for p in problems:
            print("  ", p)
        return 1

    RESULTS.mkdir(parents=True, exist_ok=True)
    cols = list(flat[0].keys())
    tab = Table(rows=[[r[c] for c in cols] for r in flat], names=cols)
    tab.meta["ledger_version"] = LEDGER_VERSION
    tab.meta["built_utc"] = datetime.now(timezone.utc).isoformat()
    tab.meta["n_surveys"] = len(surveys)
    tab.meta["schema"] = "surveys/programme-ledger/harvest/SCHEMA.md"
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    tab.write(RUN_DIR / "programme_ledger_v2.ecsv", format="ascii.ecsv", overwrite=True)
    compact = tab[(tab["channel"] != "corridor") | (tab["target_id"] == "programme")]
    compact.write(RESULTS / "programme_ledger_v2_crossings.ecsv", format="ascii.ecsv", overwrite=True)

    matrix = build_matrix(flat, registry_ids)
    (RESULTS / "programme_ledger_v2_matrix.json").write_text(json.dumps(matrix, indent=1, sort_keys=True))

    by = lambda key: dict(sorted(Counter(r[key] for r in flat).items()))  # noqa: E731
    per_survey = {s["survey_id"]: {"rows": sum(1 for r in flat if r["survey_id"] == s["survey_id"]),
                                   "harvest_rows": len(s.get("rows") or []),
                                   "candidates": s.get("candidates"), "pipeline": s.get("pipeline"),
                                   "plan_section": s.get("plan_section"), "report": s.get("report"),
                                   "statuses": dict(Counter(r["status"] for r in flat if r["survey_id"] == s["survey_id"]))}
                  for s in surveys}
    targets_with_limit = sorted({r["target_id"] for r in flat if r["status"] in ("searched", "constraint_only")
                                 and (np.isfinite(r["power_mw"]) or np.isfinite(r["power_mw_hi"])) and r["target_id"] != "programme"})
    summary = {
        "ledger_version": LEDGER_VERSION, "n_rows": len(flat), "n_surveys": len(surveys),
        "n_harvest_rows": sum(len(s.get("rows") or []) for s in surveys),
        "candidates_total": sum(int(s.get("candidates") or 0) for s in surveys),
        "by_status": by("status"), "by_channel": by("channel"), "by_rung_class": by("rung_class"),
        "by_pipeline": by("pipeline"),
        "n_targets_named": len({r["target_id"] for r in flat} - {"programme"}),
        "n_registry_targets": len(registry_ids),
        "targets_never_named": sorted(registry_ids - {r["target_id"] for r in flat}),
        "n_targets_with_power_limit": len(targets_with_limit),
        "per_survey": per_survey,
    }
    (RESULTS / "programme_ledger_v2_summary.json").write_text(json.dumps(summary, indent=1))

    env = {"sgl-seti-survey": git_commit(ROOT), "sglseti": git_commit(ROOT.parent / "sglseti"),
           "python": sys.version.split()[0]}
    runs, cons, cands = make_records(surveys, flat, registry, env)
    rec_dir = RUN_DIR / "records"
    rec_dir.mkdir(parents=True, exist_ok=True)
    for name in ("analysis_run", "constraint", "candidate"):
        (rec_dir / f"{name}.jsonl").unlink(missing_ok=True)
    append_records(rec_dir / "analysis_run.jsonl", runs)
    append_records(rec_dir / "constraint.jsonl", cons)
    append_records(rec_dir / "candidate.jsonl", cands)
    files = {f.name: f for f in sorted(HARVEST.glob("*.yaml"))}
    files.update({f"records/{n}": rec_dir / f"{n}.jsonl" for n in ("analysis_run", "constraint", "candidate")})
    files.update({f"generated/{f.name}": f for f in sorted(HARVEST_GEN.glob("*.yaml"))})
    files["ledger"] = RUN_DIR / "programme_ledger_v2.ecsv"
    files["ledger_crossings"] = RESULTS / "programme_ledger_v2_crossings.ecsv"
    man = build_manifest(files, stage="programme-ledger", schema_version=LEDGER_VERSION,
                         extra={"registry_source_hash": registry.source_hash, "environment": env,
                                "n_runs": len(runs), "n_constraints": len(cons), "n_candidates": len(cands)})
    write_manifest(RUN_DIR / "manifest.json", man)
    print(json.dumps({k: v for k, v in summary.items() if k != "per_survey"}, indent=1))
    print(f"records: {len(runs)} runs, {len(cons)} constraints, {len(cands)} candidates -> {rec_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
